version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=currencycheckproject.settings
  db:
    image: postgres
    environment:
      POSTGRES_DB: currencycheckDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
