version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=currencycheckproject.settings
    networks:
      - mynetwork

  celery:
    build: .
    depends_on:
      - redis
    command: celery -A currencycheckproject worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=currencycheckproject.settings
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_DB: currencycheckDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
